version: '3'
services:
  db:
    image: postgres:14.0-alpine
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password